title: Yuanwen Tian
logo: /assets/img/logo.png
description: Welcome to my GitHub Pages. I love Chinese calligraphy and Chinese ink painting. （keypoint- Art and Design.  unity of opposites）
email: yuanwentian@hust.edu.cn
url: yuanwentian.github.io
show_downloads: true
google_analytics: UA-127412091-1
theme: jekyll-theme-minimal
