title: Yuanwen Tian
logo: /assets/img/logo.png
description: Hi, welcome to my GitHub Pages. I'm just a young man who is trying to explore the world in both scientific and artistic way. I believe science and art tend to coalesce in moulding one's personality. My two favorite things are coding and Chinese calligraphy.
email: yuanwentian@hust.edu.cn
url: yuanwentian.github.io
show_downloads: true
google_analytics: UA-127412091-1
theme: jekyll-theme-minimal
