title: Yuanwen Tian
logo: /assets/img/logo.png
description: Welcome to my personal website, my name is Yuanwen Tian and I am a Master student in ECE at CMU. I am inspired to become a software engineer who wants to learn, to dream and to achieve. 
email: yuanwent@andrew.cmu.edu
url: yuanwentian.github.io
show_downloads: true
google_analytics: UA-127412091-1
theme: jekyll-theme-minimal
